name: Deploy site

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-site
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: rei-yami.nekoweb.org
          nekoweb-username: rei-yami
          directory: docs

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          preview_before_deploy: true
          dist_dir: docs
